# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication.proto',
  package='communication',
  serialized_pb=_b('\n\x13\x63ommunication.proto\x12\rcommunication\"g\n\x0b\x45nvironment\x12\x0c\n\x04size\x18\x01 \x02(\x05\x12\x12\n\nbaseStartX\x18\x02 \x02(\x05\x12\x12\n\nbaseStartY\x18\x03 \x02(\x05\x12\x10\n\x08\x62\x61seEndX\x18\x04 \x02(\x05\x12\x10\n\x08\x62\x61seEndY\x18\x05 \x02(\x05\"%\n\x05\x45vent\x12\r\n\x05robot\x18\x01 \x02(\x05\x12\r\n\x05stage\x18\x02 \x02(\x05\"^\n\x04Path\x12\r\n\x05robot\x18\x01 \x01(\x05\x12(\n\x05stage\x18\x02 \x03(\x0b\x32\x19.communication.Path.Stage\x1a\x1d\n\x05Stage\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\"d\n\x05Robot\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04posX\x18\x02 \x02(\x05\x12\x0c\n\x04posY\x18\x03 \x02(\x05\x12\x10\n\x05speed\x18\x04 \x01(\x01:\x01\x32\x12!\n\x04path\x18\x06 \x01(\x0b\x32\x13.communication.Path')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='communication.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='communication.Environment.size', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseStartX', full_name='communication.Environment.baseStartX', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseStartY', full_name='communication.Environment.baseStartY', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseEndX', full_name='communication.Environment.baseEndX', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baseEndY', full_name='communication.Environment.baseEndY', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=141,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='communication.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot', full_name='communication.Event.robot', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stage', full_name='communication.Event.stage', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=180,
)


_PATH_STAGE = _descriptor.Descriptor(
  name='Stage',
  full_name='communication.Path.Stage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='communication.Path.Stage.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='communication.Path.Stage.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=276,
)

_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='communication.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot', full_name='communication.Path.robot', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stage', full_name='communication.Path.stage', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PATH_STAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=276,
)


_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='communication.Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='communication.Robot.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posX', full_name='communication.Robot.posX', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posY', full_name='communication.Robot.posY', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='communication.Robot.speed', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='communication.Robot.path', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=378,
)

_PATH_STAGE.containing_type = _PATH
_PATH.fields_by_name['stage'].message_type = _PATH_STAGE
_ROBOT.fields_by_name['path'].message_type = _PATH
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENT,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communication.Environment)
  ))
_sym_db.RegisterMessage(Environment)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communication.Event)
  ))
_sym_db.RegisterMessage(Event)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(

  Stage = _reflection.GeneratedProtocolMessageType('Stage', (_message.Message,), dict(
    DESCRIPTOR = _PATH_STAGE,
    __module__ = 'communication_pb2'
    # @@protoc_insertion_point(class_scope:communication.Path.Stage)
    ))
  ,
  DESCRIPTOR = _PATH,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communication.Path)
  ))
_sym_db.RegisterMessage(Path)
_sym_db.RegisterMessage(Path.Stage)

Robot = _reflection.GeneratedProtocolMessageType('Robot', (_message.Message,), dict(
  DESCRIPTOR = _ROBOT,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:communication.Robot)
  ))
_sym_db.RegisterMessage(Robot)


# @@protoc_insertion_point(module_scope)
